"""3D toolpath viewer (Phase 4, ADR-004).

Parses a BioSlice5X-emitted G-code file and renders the toolpath in a
PyVista window. Extrusion moves are colored by Z height; travel moves
render as a single grey segment bundle; tool-orientation arrows are
drawn at every Nth extrusion sample on tilt_swivel chains.

The viewer is intentionally self-contained — it consumes a G-code file,
not the slicer's in-memory SliceResult. Phase 5 will add a sibling
constructor that takes a SliceResult directly so per-move shear-stress
coloring works (the G-code header carries summary stats but not per-move
detail; see ADR-004 §Out of scope).

API:

    from bioslice5x.visualization import preview_gcode
    preview_gcode("cube.gcode")                            # opens a window
    preview_gcode("cube.gcode", screenshot="cube.png")     # saves an image
    preview_gcode("cube.gcode", show=False, screenshot="cube.png")

The CLI surface is `bioslice5x preview <gcode>` (see bioslice5x.cli).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any, Literal

ColorMode = Literal["z", "shear"]

if TYPE_CHECKING:
    import numpy.typing as npt

# G-code token regex. Captures `X12.3`, `A-30`, `E0.05`, etc. Float values
# may be integer-formatted ("X5") or with a decimal point ("X5.123").
_TOKEN_RE = re.compile(r"([XYZACEFB])(-?\d+(?:\.\d+)?)")
_META_RE = re.compile(r"^;META:\s+(\w+)\s*=\s*(\S+)\s*$")
_HEADER_FIELD_RE = re.compile(r"^;\s+(.+?):\s+(.+?)\s*$")
# Per-segment wall shear stress, emitted by the postprocessor as a
# trailing comment on each extrusion G1 line: `;STRESS:<Pa>`. Optional —
# G-code generated by older slicer versions, or by external tools, will
# parse without the token and `ParsedMove.wall_shear_pa` will be None.
_STRESS_RE = re.compile(r";STRESS:(-?\d+(?:\.\d+)?)")


@dataclass(frozen=True)
class ParsedMove:
    """A single G1 segment, parsed from emitted G-code.

    Coordinates are machine-frame absolute (X/Y/Z) plus the rotary axis
    letters that appear on the move (A, B, C). The viewer maps these
    to syringe orientation: for now, A is tilt-about-X, B is tilt-about-Y,
    and C is swivel-about-Z by the Open5X conventions; future profiles
    that differ would need a profile-aware parser, but most G-code in
    the wild will use these letters.
    """

    end_xyz: tuple[float, float, float]
    is_travel: bool
    a_deg: float | None
    b_deg: float | None
    c_deg: float | None
    extrusion_uL: float
    feed_mm_per_min: float
    # Wall shear stress (Pa) read from the `;STRESS:<Pa>` trailing
    # comment that the postprocessor emits per extrusion move. None
    # when the move is a travel, or when the G-code was produced by a
    # tool that does not emit the stress token. The viewer's "shear"
    # color mode requires this to be populated.
    wall_shear_pa: float | None


def parse_gcode(path: str | Path) -> tuple[list[ParsedMove], dict[str, str]]:
    """Parse a BioSlice5X G-code file into a list of moves + a header map.

    The header map carries the `;META: key=value` block plus the
    free-text `; Key: value` header fields. Returned as a `dict[str, str]`.

    Empty G-code files (no G1 lines) return an empty move list and the
    header map, which lets the viewer render the build volume even when
    the toolpath is degenerate.
    """
    text = Path(path).read_text(encoding="utf-8")
    moves: list[ParsedMove] = []
    header: dict[str, str] = {}
    # Track running absolute position; first move starts at (0, 0, 0)
    # by convention (the G-code header includes a G90 absolute-mode line).
    cur_x = cur_y = cur_z = 0.0
    cur_a: float | None = None
    cur_b: float | None = None
    cur_c: float | None = None
    in_print = False
    for line in text.splitlines():
        stripped = line.strip()
        # Header parsing: prose fields, then META block.
        meta = _META_RE.match(stripped)
        if meta:
            header[f"meta.{meta.group(1)}"] = meta.group(2)
            continue
        header_field = _HEADER_FIELD_RE.match(stripped)
        if header_field and not in_print:
            header[header_field.group(1)] = header_field.group(2)
        if stripped == "; ---- start of print ----":
            in_print = True
            continue
        if stripped == "; ---- end of print ----":
            in_print = False
            continue
        if not in_print or not stripped.startswith("G1"):
            continue
        # Parse the G1 line.
        tokens = dict(_TOKEN_RE.findall(stripped))
        if not tokens:
            continue
        new_x = float(tokens["X"]) if "X" in tokens else cur_x
        new_y = float(tokens["Y"]) if "Y" in tokens else cur_y
        new_z = float(tokens["Z"]) if "Z" in tokens else cur_z
        new_a = float(tokens["A"]) if "A" in tokens else cur_a
        new_b = float(tokens["B"]) if "B" in tokens else cur_b
        new_c = float(tokens["C"]) if "C" in tokens else cur_c
        extrusion = float(tokens.get("E", "0"))
        feed = float(tokens.get("F", "0"))
        # Travel moves don't carry an E token in BioSlice5X output.
        is_travel = "E" not in tokens
        stress_match = _STRESS_RE.search(stripped)
        wall_shear_pa: float | None = float(stress_match.group(1)) if stress_match else None
        moves.append(
            ParsedMove(
                end_xyz=(new_x, new_y, new_z),
                is_travel=is_travel,
                a_deg=new_a,
                b_deg=new_b,
                c_deg=new_c,
                extrusion_uL=extrusion,
                feed_mm_per_min=feed,
                wall_shear_pa=wall_shear_pa,
            )
        )
        cur_x, cur_y, cur_z = new_x, new_y, new_z
        cur_a, cur_b, cur_c = new_a, new_b, new_c
    return moves, header


def _compute_layer_indices(ext_moves: list[ParsedMove]) -> npt.NDArray[Any]:
    """Assign a layer index to each extrusion move.

    Flat and wrap-around-Z prints climb monotonically in Z; binning by
    rounded Z (to 0.01 mm) produces a stable, intuitive layer count
    matching the slicer's `layer_height_mm`. For conformal / 5-axis
    prints where Z is non-monotonic and varies continuously, the
    rounded-Z scheme produces too many "layers" (one per sample point);
    in that case fall back to splitting the move sequence into 100
    equal-count bands, which still gives a useful scrubber.

    Returns an int64 array of shape (len(ext_moves),). Layer 0 is the
    first to be printed; the slider's max value is `layer_indices.max()`.
    """
    import numpy as np

    if not ext_moves:
        return np.empty((0,), dtype=np.int64)
    zs = np.array([m.end_xyz[2] for m in ext_moves], dtype=np.float64)
    # Round to 10 µm to absorb floating-point jitter.
    z_rounded = np.round(zs * 100.0) / 100.0
    distinct = np.unique(z_rounded)
    # If most moves share a Z (flat / wrap-Z), use rounded-Z layers.
    # Threshold: <=1 distinct Z per 5 moves = "Z-banded enough to scrub".
    if len(distinct) <= max(1, len(ext_moves) // 5):
        rank = {z: i for i, z in enumerate(np.sort(distinct))}
        return np.array([rank[float(z)] for z in z_rounded], dtype=np.int64)
    # Conformal / 5-axis fallback: 100 equal-count bands over move order.
    n_bands = min(100, len(ext_moves))
    return np.array(
        [min(int(i * n_bands / len(ext_moves)), n_bands - 1) for i in range(len(ext_moves))],
        dtype=np.int64,
    )


def _segment_arrays(
    moves: list[ParsedMove],
) -> tuple[npt.NDArray[Any], npt.NDArray[Any], list[ParsedMove]]:
    """Return (extrusion_segment_points, travel_segment_points, extrusion_moves).

    The extrusion-moves list is parallel to the extrusion-segment array — one
    move per pair of points. Callers compute per-segment scalars (Z, shear,
    layer index, …) from this list.
    """
    import numpy as np

    extrusion_segs: list[tuple[tuple[float, float, float], tuple[float, float, float]]] = []
    travel_segs: list[tuple[tuple[float, float, float], tuple[float, float, float]]] = []
    extrusion_moves: list[ParsedMove] = []
    cur = (0.0, 0.0, 0.0)
    for move in moves:
        seg = (cur, move.end_xyz)
        if move.is_travel:
            travel_segs.append(seg)
        else:
            extrusion_segs.append(seg)
            extrusion_moves.append(move)
        cur = move.end_xyz
    ext_arr = np.array(extrusion_segs).reshape(-1, 3) if extrusion_segs else np.empty((0, 3))
    trv_arr = np.array(travel_segs).reshape(-1, 3) if travel_segs else np.empty((0, 3))
    return ext_arr, trv_arr, extrusion_moves


def _orientation_arrow_points(
    moves: list[ParsedMove], sample_every: int
) -> tuple[npt.NDArray[Any], npt.NDArray[Any]]:
    """Compute arrow origin points and direction vectors at sampled moves.

    The arrows show the *part's local orientation* under each move's
    rotary configuration — concretely, where the syringe (which stays
    vertical in machine frame) lands relative to the rotated bed.

    For each sampled move with non-zero rotary angles:
    - Origin = the move's end XYZ in machine frame
    - Direction = (0, 0, 1) rotated by the inverse of (A about X) and
      (C about Z), which gives the syringe's direction in part frame
      (i.e., where on the part the deposition is landing).

    Tilt-about-Y (B) profiles substitute Y for X in the tilt rotation.

    Returns (origins[N, 3], directions[N, 3]).
    """
    import numpy as np

    origins: list[tuple[float, float, float]] = []
    directions: list[tuple[float, float, float]] = []
    extrusions = [m for m in moves if not m.is_travel]
    for i in range(0, len(extrusions), max(1, sample_every)):
        m = extrusions[i]
        a = np.radians(m.a_deg) if m.a_deg is not None else 0.0
        b = np.radians(m.b_deg) if m.b_deg is not None else 0.0
        c = np.radians(m.c_deg) if m.c_deg is not None else 0.0
        # Inverse of (R_tilt · R_swivel) applied to +Z. Tilt is around X
        # (A) or Y (B); swivel is around Z (C). Both are right-hand rule.
        # Compose inverse: R_swivel(-c) · R_tilt(-a or -b) · (0, 0, 1)
        # tilt_inverse:
        cz_inv = np.cos(-c)
        sz_inv = np.sin(-c)
        if a != 0.0:
            cx_inv = np.cos(-a)
            sx_inv = np.sin(-a)
            # R_x(-a) on (0, 0, 1) → (0, sin(a), cos(a)) — sin/cos swap due to inverse
            after_tilt = (0.0, -sx_inv * 1.0, cx_inv * 1.0)
        elif b != 0.0:
            cy_inv = np.cos(-b)
            sy_inv = np.sin(-b)
            # R_y(-b) on (0, 0, 1) → (-sin(-b), 0, cos(-b)) = (sin(b), 0, cos(b))
            after_tilt = (sy_inv * 1.0, 0.0, cy_inv * 1.0)
        else:
            after_tilt = (0.0, 0.0, 1.0)
        # R_z(-c) on after_tilt
        x, y, z = after_tilt
        dx = cz_inv * x - sz_inv * y
        dy = sz_inv * x + cz_inv * y
        dz = z
        # Skip arrows that point near-vertically — they're indistinguishable
        # from the identity case and add visual noise.
        if abs(dx) < 1e-6 and abs(dy) < 1e-6 and abs(dz - 1.0) < 1e-6:
            continue
        origins.append(m.end_xyz)
        directions.append((float(dx), float(dy), float(dz)))
    if not origins:
        return np.empty((0, 3)), np.empty((0, 3))
    return np.array(origins), np.array(directions)


class ToolpathViewer:
    """Encapsulates the PyVista plotter for one G-code file.

    Construct with a parsed move list + header dict, then call `.show()`
    to open the interactive window or `.screenshot(path)` for headless
    rendering.
    """

    def __init__(
        self,
        moves: list[ParsedMove],
        header: dict[str, str],
        *,
        build_volume: tuple[tuple[float, float], tuple[float, float], tuple[float, float]]
        | None = None,
        arrow_sample_every: int = 50,
        title: str = "BioSlice5X toolpath",
        color_by: ColorMode = "z",
        cell_stress_threshold_pa: float | None = None,
        show_layer_slider: bool = True,
        source_mesh_path: str | Path | None = None,
        source_mesh_opacity: float = 0.15,
    ) -> None:
        self.moves = moves
        self.header = header
        self.build_volume = build_volume
        self.arrow_sample_every = arrow_sample_every
        self.title = title
        # Layer scrubber: when True (default in interactive mode), the
        # viewer adds a PyVista slider that controls how many layers of
        # the print are visible. Headless screenshot rendering disables
        # this (no interactor to back the widget).
        self.show_layer_slider = show_layer_slider
        # Source-mesh overlay (the original STL). When set, the viewer
        # renders the mesh semi-transparent so the user can compare
        # "what was asked for" against "what was sliced". The mesh is
        # rendered in its native coordinate frame; flat-orientation
        # prints align with the toolpath. Prints with a fixed-tilt
        # orientation will show the mesh in the part frame, offset from
        # the machine-frame toolpath — a known limitation, surfaced in
        # the info overlay.
        self.source_mesh_path = Path(source_mesh_path) if source_mesh_path is not None else None
        self.source_mesh_opacity = source_mesh_opacity
        # Set by `_build_plotter` — pre-declared for mypy --strict.
        self._source_mesh_error: str | None = None
        self._shear_fallback_to_z: bool = False
        # Color mode: "z" colors extrusion moves by Z height (the v0.1.0
        # default — anatomy of the print). "shear" colors them by the
        # per-segment wall shear stress emitted as `;STRESS:` tokens by
        # the postprocessor. If "shear" is selected but no move carries a
        # stress entry (legacy / third-party G-code), `_build_plotter`
        # falls back to "z" with a warning text overlay.
        self.color_by: ColorMode = color_by
        # The cell-payload threshold for the active syringe, in Pa. When
        # supplied alongside color_by="shear", the colormap is clamped to
        # [0, threshold] so the operator sees red exactly when the safety
        # limit is breached. If unset, the colormap auto-fits to the data.
        self.cell_stress_threshold_pa = cell_stress_threshold_pa

    def _build_plotter(self, off_screen: bool = False) -> Any:
        try:
            import numpy as np
            import pyvista as pv
        except ImportError as exc:
            raise RuntimeError(
                "The toolpath viewer requires PyVista. Install with: "
                "`uv pip install 'bioslice5x[viz]'` or `pip install pyvista`."
            ) from exc

        # PyVista's stubs decorate several methods (`set_background`,
        # `show_axes`) in a way that confuses mypy --strict; the methods
        # exist and work at runtime. Annotate the local as Any to opt out
        # of those false positives without suppressing real type checks.
        plotter: Any = pv.Plotter(off_screen=off_screen, title=self.title)
        plotter.set_background("white")

        # Build-volume wireframe (if provided).
        if self.build_volume is not None:
            (x0, x1), (y0, y1), (z0, z1) = self.build_volume
            box = pv.Box(bounds=(x0, x1, y0, y1, z0, z1))
            plotter.add_mesh(
                box,
                style="wireframe",
                color="lightgrey",
                line_width=1,
                opacity=0.5,
                name="build_volume",
            )

        # Source-mesh overlay (the original STL/OBJ). Loaded via trimesh
        # then converted to PyVista PolyData. Rendered semi-transparent
        # so the underlying toolpath stays visible — the operator can
        # spot regions where the toolpath escapes the mesh envelope.
        if self.source_mesh_path is not None:
            try:
                import trimesh as _tm

                mesh: Any = _tm.load(str(self.source_mesh_path), force="mesh")
                # PyVista expects a flat face array prefixed with point-counts.
                # trimesh stores triangles as (N, 3). Convert to PyVista's
                # (N, 4) layout: [3, a, b, c, 3, d, e, f, ...].
                tris = np.asarray(mesh.faces, dtype=np.int64)
                vertices = np.asarray(mesh.vertices, dtype=np.float64)
                faces_flat = np.column_stack([np.full(len(tris), 3, dtype=np.int64), tris]).ravel()
                pv_mesh = pv.PolyData(vertices, faces_flat)
                plotter.add_mesh(
                    pv_mesh,
                    color="lightblue",
                    opacity=self.source_mesh_opacity,
                    name="source_mesh",
                    show_edges=False,
                )
            except Exception as exc:
                # Mesh load is best-effort — surface the failure in the
                # info overlay but render the rest of the scene.
                self._source_mesh_error = f"failed to load source mesh: {exc}"
            else:
                self._source_mesh_error = None
        else:
            self._source_mesh_error = None

        ext_pts, trv_pts, ext_moves = _segment_arrays(self.moves)

        # Pick the per-segment scalar and colormap based on color mode.
        # When "shear" is requested but the G-code lacks `;STRESS:` tokens,
        # fall back to "z" and report the fallback in the info overlay
        # later in this method.
        active_mode: ColorMode = self.color_by
        if active_mode == "shear" and not any(m.wall_shear_pa is not None for m in ext_moves):
            active_mode = "z"
            self._shear_fallback_to_z = True
        else:
            self._shear_fallback_to_z = False

        # Extrusion moves — colored by the active scalar.
        if len(ext_pts) > 0:
            n_segments = len(ext_pts) // 2
            cells = np.column_stack(
                [
                    np.full(n_segments, 2, dtype=np.int64),
                    np.arange(0, 2 * n_segments, 2, dtype=np.int64),
                    np.arange(1, 2 * n_segments + 1, 2, dtype=np.int64),
                ]
            ).ravel()
            ext_lines = pv.PolyData(ext_pts, lines=cells)
            scalar_args: dict[str, Any]
            if active_mode == "shear":
                # Per-segment stress, two vertices per segment.
                stresses = np.array(
                    [m.wall_shear_pa if m.wall_shear_pa is not None else 0.0 for m in ext_moves],
                    dtype=np.float64,
                )
                ext_lines["wall_shear_pa"] = np.repeat(stresses, 2)[: 2 * n_segments]
                # Use "hot" colormap: low stress → black, high stress → white-hot.
                # Clip to [0, threshold] when threshold is supplied so red
                # appears exactly at the cell-viability limit; otherwise auto-fit.
                clim: tuple[float, float] | None = (
                    (0.0, self.cell_stress_threshold_pa)
                    if self.cell_stress_threshold_pa is not None
                    else None
                )
                scalar_args = {
                    "scalars": "wall_shear_pa",
                    "cmap": "hot",
                    "scalar_bar_args": {"title": "Wall shear (Pa)"},
                }
                if clim is not None:
                    scalar_args["clim"] = clim
            else:
                # Color by Z height — the v0.1.0 default.
                zs = np.array([m.end_xyz[2] for m in ext_moves], dtype=np.float64)
                ext_lines["z_height"] = np.repeat(zs, 2)[: 2 * n_segments]
                scalar_args = {
                    "scalars": "z_height",
                    "cmap": "viridis",
                    "scalar_bar_args": {"title": "Z (mm)"},
                }
            # Layer index per segment — for the scrubber and for the
            # info overlay. Computed even when the slider is off so the
            # scalar lives on the polydata and downstream tooling can
            # query it.
            ext_layer_indices = _compute_layer_indices(ext_moves)
            ext_lines.cell_data["layer_index"] = ext_layer_indices
            max_layer = int(ext_layer_indices.max()) if len(ext_layer_indices) else 0

            plotter.add_mesh(
                ext_lines,
                line_width=2,
                show_scalar_bar=True,
                name="extrusion",
                **scalar_args,
            )

            # Layer scrubber slider — disabled when rendering off-screen
            # (no VTK interactor to back the widget) or when there's only
            # a single layer (trivial scrubber adds no information).
            if self.show_layer_slider and not off_screen and max_layer > 0:
                # The slider sets the upper bound on visible layers. We
                # re-build the extrusion actor each frame by thresholding
                # the per-cell `layer_index` array. The `name="extrusion"`
                # tag means the new actor replaces the existing one.
                ext_lines_ref = ext_lines  # close over the original polydata
                local_scalar_args = scalar_args  # close over the color spec

                def _on_layer_change(value: float) -> None:
                    n_visible = max(0, round(value))
                    filtered = ext_lines_ref.threshold(
                        value=(-0.5, n_visible + 0.5),
                        scalars="layer_index",
                        preference="cell",
                    )
                    plotter.add_mesh(
                        filtered,
                        line_width=2,
                        show_scalar_bar=False,  # avoid duplicating the colorbar
                        name="extrusion",
                        **local_scalar_args,
                    )

                plotter.add_slider_widget(
                    callback=_on_layer_change,
                    rng=[0, max_layer],
                    value=max_layer,
                    title=f"Layers shown (0..{max_layer})",
                    pointa=(0.05, 0.05),
                    pointb=(0.45, 0.05),
                    event_type="always",
                )

        # Travel moves — single grey colour, thinner.
        if len(trv_pts) > 0:
            n_trv_segments = len(trv_pts) // 2
            trv_cells = np.column_stack(
                [
                    np.full(n_trv_segments, 2, dtype=np.int64),
                    np.arange(0, 2 * n_trv_segments, 2, dtype=np.int64),
                    np.arange(1, 2 * n_trv_segments + 1, 2, dtype=np.int64),
                ]
            ).ravel()
            trv_lines = pv.PolyData(trv_pts, lines=trv_cells)
            plotter.add_mesh(trv_lines, color="lightgrey", line_width=1, opacity=0.6, name="travel")

        # Tool-orientation arrows.
        origins, directions = _orientation_arrow_points(self.moves, self.arrow_sample_every)
        if len(origins) > 0:
            plotter.add_arrows(
                origins,
                directions,
                mag=2.0,
                color="red",
                name="tool_orientation",
            )

        # Title overlay with key header metadata.
        info_lines = [
            f"BioSlice5X toolpath: {self.title}",
            f"Moves: {len(self.moves)}",
        ]
        # Surface the color mode and the shear-fallback path.
        info_lines.append(f"Color: {active_mode}")
        if self._shear_fallback_to_z:
            info_lines.append("(shear requested but G-code lacks ;STRESS: tokens — fell back to z)")
        if self.color_by == "shear" and self.cell_stress_threshold_pa is not None:
            info_lines.append(f"Cell threshold: {self.cell_stress_threshold_pa:.0f} Pa")
        if self.source_mesh_path is not None:
            if self._source_mesh_error:
                info_lines.append(self._source_mesh_error)
            else:
                info_lines.append(f"Mesh overlay: {self.source_mesh_path.name}")
        if "Profile" in self.header:
            info_lines.append(f"Profile: {self.header['Profile']}")
        if "Recipe" in self.header:
            info_lines.append(f"Recipe: {self.header['Recipe']}")
        if "meta.kinematic_chain" in self.header:
            info_lines.append(f"Kinematic: {self.header['meta.kinematic_chain']}")
        if "meta.bioink_calibration" in self.header:
            cal = self.header["meta.bioink_calibration"]
            colour = "red" if cal == "uncalibrated" else "black"
            info_lines.append(f"Bioink: {cal}")
            # Calibration banner colour cue: red for uncalibrated.
            plotter.add_text(
                "\n".join(info_lines),
                position="upper_left",
                font_size=10,
                color=colour,
                name="info",
            )
        else:
            plotter.add_text(
                "\n".join(info_lines),
                position="upper_left",
                font_size=10,
                color="black",
                name="info",
            )

        plotter.show_axes()
        plotter.camera.azimuth = 30
        plotter.camera.elevation = 20

        return plotter

    def show(self) -> None:
        """Open the interactive PyVista window. Blocks until the user closes it."""
        plotter = self._build_plotter(off_screen=False)
        plotter.show()

    def screenshot(self, path: str | Path) -> None:
        """Render the toolpath to a PNG without opening a window. Useful for CI."""
        plotter = self._build_plotter(off_screen=True)
        plotter.screenshot(str(path))
        plotter.close()


def preview_gcode(
    path: str | Path,
    *,
    build_volume: tuple[tuple[float, float], tuple[float, float], tuple[float, float]]
    | None = None,
    arrow_sample_every: int = 50,
    show: bool = True,
    screenshot: str | Path | None = None,
    color_by: ColorMode = "z",
    cell_stress_threshold_pa: float | None = None,
    show_layer_slider: bool = True,
    source_mesh_path: str | Path | None = None,
    source_mesh_opacity: float = 0.15,
) -> ToolpathViewer:
    """Parse a G-code file and open the viewer.

    `build_volume` is the machine-frame bounding box from the profile;
    if None, the viewer auto-fits the toolpath. Pass `show=False` and
    `screenshot=<path>` for headless rendering (CI, scripts, tests).

    `color_by` selects the extrusion-segment color scalar — "z" (default,
    by Z height, like PrusaSlicer's height overlay) or "shear" (by the
    `;STRESS:<Pa>` token written by the postprocessor). When `color_by="shear"`
    and `cell_stress_threshold_pa` is supplied, the colormap is clamped to
    [0, threshold] so the red end of the scale marks the cell-viability
    limit exactly. If the G-code doesn't carry stress tokens, the viewer
    falls back to "z" and surfaces the fallback in the info overlay.
    """
    moves, header = parse_gcode(path)
    viewer = ToolpathViewer(
        moves=moves,
        header=header,
        build_volume=build_volume,
        arrow_sample_every=arrow_sample_every,
        title=Path(path).name,
        color_by=color_by,
        cell_stress_threshold_pa=cell_stress_threshold_pa,
        show_layer_slider=show_layer_slider,
        source_mesh_path=source_mesh_path,
        source_mesh_opacity=source_mesh_opacity,
    )
    if screenshot is not None:
        viewer.screenshot(screenshot)
    if show:
        viewer.show()
    return viewer


__all__ = [
    "ColorMode",
    "ParsedMove",
    "ToolpathViewer",
    "parse_gcode",
    "preview_gcode",
]
